import { UploadWorkflowError } from "./upload-errors";
import { getSafeFileExtension } from "./file-validation";
import { uploadBookCover } from "./blob-upload";

type UploadCoverInput = {
  uploadBasePath: string;
  fileTitle: string;
  manualCoverFile?: File;
  autoCoverDataUrl: string;
};

export const uploadCoverImage = async ({
  uploadBasePath,
  fileTitle,
  manualCoverFile,
  autoCoverDataUrl,
}: UploadCoverInput) => {
  if (manualCoverFile) {
    const extension = getSafeFileExtension(manualCoverFile, "png");

    return uploadBookCover(
      `${uploadBasePath}/${fileTitle}-cover.${extension}`,
      manualCoverFile,
      manualCoverFile.type || "image/png",
    );
  }

  return uploadAutoGeneratedCover({
    uploadBasePath,
    fileTitle,
    coverDataUrl: autoCoverDataUrl,
  });
};

const uploadAutoGeneratedCover = async ({
  uploadBasePath,
  fileTitle,
  coverDataUrl,
}: {
  uploadBasePath: string;
  fileTitle: string;
  coverDataUrl: string;
}) => {
  const coverBlob = await fetchBlobFromDataUrl(coverDataUrl);

  return uploadBookCover(
    `${uploadBasePath}/${fileTitle}-cover.png`,
    coverBlob,
    coverBlob.type || "image/png",
  );
};

const fetchBlobFromDataUrl = async (dataUrl: string) => {
  const response = await fetch(dataUrl);

  if (!response.ok) {
    throw new UploadWorkflowError(
      "Unable to prepare the generated cover image.",
      "AUTO_COVER_FETCH_FAILED",
    );
  }

  const blob = await response.blob();

  if (blob.size === 0) {
    throw new UploadWorkflowError(
      "The generated cover image was empty.",
      "AUTO_COVER_EMPTY",
    );
  }

  return blob;
};
